habits/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add_goal/', views.add_goal, name='add_goal'),
    path('add_habit/', views.add_habit, name='add_habit'),
    path('add_study_day/', views.add_study_day, name='add_study_day'),
    path('delete_goal/<int:goal_id>/', views.delete_goal, name='delete_goal'),
    path('update_goal/<int:goal_id>/', views.update_goal, name='update_goal'),
]

improductive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('habits.urls')),
]

habits/models.py
from django.db import models
import datetime


class CategoryHabit(models.Model):
    name = models.CharField(max_length=255)
    date_current = models.DateTimeField(
        default=datetime.datetime.now)  # Proveer un valor por defecto

    def __str__(self):
        return self.name


class Month(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Goal(models.Model):
    goal = models.FloatField()
    category = models.ForeignKey(CategoryHabit, on_delete=models.CASCADE)
    month = models.ForeignKey(Month, on_delete=models.CASCADE)
    date_current = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.category.name} - {self.month.name}"


class Habit(models.Model):
    study_time = models.FloatField()
    category = models.ForeignKey(CategoryHabit, on_delete=models.CASCADE)
    date_current = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.category.name} - {self.study_time} hours"


class StudyDay(models.Model):
    category = models.ForeignKey(CategoryHabit, on_delete=models.CASCADE)
    study_time = models.FloatField()
    date_current = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.category.name} - {self.study_time} hours on {self.date_current}"

habits/forms.py
from django import forms
from .models import Habit, Goal, StudyDay, CategoryHabit


class HabitForm(forms.ModelForm):
    class Meta:
        model = CategoryHabit
        fields = ['name']


class GoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        fields = ['goal', 'category', 'month']


class StudyDayForm(forms.ModelForm):
    class Meta:
        model = StudyDay
        fields = ['study_time', 'category']

habits/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Goal, CategoryHabit, Month, Habit, StudyDay
from .forms import GoalForm, HabitForm, StudyDayForm
from django.utils import timezone
import datetime
import matplotlib.pyplot as plt
import io
import urllib
import base64


def index(request):
    current_month = timezone.now().strftime("%B")
    goals = Goal.objects.filter(month__name=current_month)
    study_days = StudyDay.objects.all()
    chart = generate_chart(study_days, goals)
    context = {
        'goals': goals,
        'study_days': study_days,
        'chart': chart,
        'form': StudyDayForm(),
    }
    return render(request, 'habits/index.html', context)


def generate_chart(study_days, goals):
    fig, ax = plt.subplots(figsize=(9, 5), dpi=200)
    ax.set_title("Study Goals and Progress")
    ax.set_xlabel("Goals")
    ax.set_ylabel("Habits")
    legend_labels = ["Goal", 'Habit within Goal',
                     "< 30% Goal", "30%-50% Goal", "> 50% Goal"]
    legend_colors = ["#C0BEBC", '#448BDB', "#FA5F4B", "#F9EC8A", "#73FA8E"]
    goals_name = [goal.category.name for goal in goals]
    goals_value = [goal.goal for goal in goals]

    ax.barh(goals_name, goals_value, color="#C0BEBC",
            edgecolor='black', label="Goals", height=0.5, alpha=0.8)
    study_names = [study.category.name for study in study_days]
    study_values = [study.study_time for study in study_days]
    colors = []

    for study in study_days:
        if study.category.name in goals_name:
            goal = goals.get(category=study.category)
            percentage = (study.study_time / goal.goal) * \
                100 if goal.goal != 0 else 0
            if percentage <= 30:
                colors.append("#FA5F4B")
            elif percentage < 50:
                colors.append("#F9EC8A")
            else:
                colors.append("#73FA8E")
        else:
            colors.append('#448BDB')

    ax.barh(study_names, study_values, color=colors, edgecolor='black',
            label="Studied Hours", height=0.5, alpha=0.8)

    legend_handles = [plt.Rectangle((0, 0), 1, 1, color=color)
                      for color in legend_colors]
    ax.legend(legend_handles, legend_labels, loc="upper right", fontsize=12)

    canvas = plt.gcf().canvas
    buf = io.BytesIO()
    canvas.print_png(buf)
    buf.seek(0)
    string = base64.b64encode(buf.read())
    uri = urllib.parse.quote(string)
    return uri


def add_goal(request):
    if request.method == "POST":
        form = GoalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = GoalForm()
    return render(request, 'habits/add_goal.html', {'form': form})


def add_habit(request):
    if request.method == "POST":
        form = HabitForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = HabitForm()
    return render(request, 'habits/add_habit.html', {'form': form})


def add_study_day(request):
    if request.method == "POST":
        form = StudyDayForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = StudyDayForm()
    return render(request, 'habits/add_study_day.html', {'form': form})


def delete_goal(request, goal_id):
    goal = get_object_or_404(Goal, id=goal_id)
    goal.delete()
    return redirect('index')


def update_goal(request, goal_id):
    goal = get_object_or_404(Goal, id=goal_id)
    if request.method == "POST":
        form = GoalForm(request.POST, instance=goal)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = GoalForm(instance=goal)
    return render(request, 'habits/update_goal.html', {'form': form})

habits/templates/habits/add_goal.html
{% extends 'habits/base.html' %}

{% block title %}Add Goal - ImProductive{% endblock %}

{% block content %}
    <h1 class="mt-4">Add Goal</h1>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

habits/templates/habits/add_habit.html
{% extends 'habits/base.html' %}

{% block title %}Add Habit - ImProductive{% endblock %}

{% block content %}
    <h1 class="mt-4">Add Habit</h1>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

habits/templates/habits/add_study_day.html
{% extends 'habits/base.html' %}

{% block title %}Add Study Time - ImProductive{% endblock %}

{% block content %}
    <h1 class="mt-4">Add Study Time</h1>
    <form method="post" class="mt-4" id="studyTimeForm">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <div class="form-group">
            <label for="timer">Timer</label>
            <div id="timer">00:00:00</div>
            <button type="button" class="btn btn-primary" onclick="startTimer()">Start</button>
            <button type="button" class="btn btn-secondary" onclick="pauseTimer()">Pause</button>
            <button type="button" class="btn btn-danger" onclick="resetTimer()">Reset</button>
        </div>
        <input type="hidden" name="study_time" id="study_time">
        <button type="submit" class="btn btn-primary" onclick="submitForm()">Save</button>
        <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
    </form>

    <script>
        let timer;
        let startTime;
        let updatedTime;
        let difference;
        let tInterval;
        let savedTime;
        let running = false;
        let paused = false;

        function startTimer() {
            if (!running) {
                startTime = new Date().getTime();
                tInterval = setInterval(getShowTime, 1);
                paused = false;
                running = true;
            }
        }

        function pauseTimer() {
            if (!paused && running) {
                clearInterval(tInterval);
                savedTime = difference;
                paused = true;
                running = false;
            }
        }

        function resetTimer() {
            clearInterval(tInterval);
            savedTime = 0;
            difference = 0;
            paused = false;
            running = false;
            document.getElementById("timer").innerHTML = "00:00:00";
        }

        function getShowTime() {
            updatedTime = new Date().getTime();
            if (savedTime) {
                difference = (updatedTime - startTime) + savedTime;
            } else {
                difference = updatedTime - startTime;
            }
            let hours = Math.floor((difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            let minutes = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
            let seconds = Math.floor((difference % (1000 * 60)) / 1000);
            hours = (hours < 10) ? "0" + hours : hours;
            minutes = (minutes < 10) ? "0" + minutes : minutes;
            seconds = (seconds < 10) ? "0" + seconds : seconds;
            document.getElementById("timer").innerHTML = hours + ":" + minutes + ":" + seconds;
        }

        function submitForm() {
            const timeArray = document.getElementById("timer").innerHTML.split(':');
            const hours = parseInt(timeArray[0]);
            const minutes = parseInt(timeArray[1]);
            const seconds = parseInt(timeArray[2]);
            const totalMinutes = (hours * 60) + minutes + (seconds / 60);
            document.getElementById("study_time").value = totalMinutes.toFixed(2);
            document.getElementById("studyTimeForm").submit();
        }
    </script>
{% endblock %}

habits/templates/habits/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'habits/css/styles.css' %}">
</head>
<body class="bg-gray-900 text-white">
    {% block content %}{% endblock %}
</body>
</html>

habits/templates/habits/chart_study_days.html
<!-- templates/chart.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Study Goals and Progress</title>
</head>
<body>
    <h1>Study Goals and Progress</h1>
    <img src="{% url 'chart_study_days' %}" alt="Chart">
</body>
</html>

habits/templates/habits/index.html
{% extends 'habits/base.html' %}
{% load static %}
{% load form_tags %}

{% block title %}Dashboard - ImProductive{% endblock %}

{% block content %}
    <div class="bg-pastel min-h-screen p-8">
        <h1 class="text-4xl font-bold mt-4 text-center text-gray-800">ImProductive Dashboard</h1>
        <div class="flex justify-center space-x-4 mt-4 mb-4">
            <button type="button" id="toggle_timer_manual" class="bg-blue-200 text-gray-800 py-2 px-3 rounded-lg hover:bg-blue-300">
                <img src="{% static 'habits/icons/toggle_timer.png' %}" alt="Toggle" class="w-8 h-8 inline">
            </button>
            <a href="{% url 'add_goal' %}" class="bg-green-200 text-gray-800 py-2 px-3 rounded-lg hover:bg-green-300">
                <img src="{% static 'habits/icons/add_goal.png' %}" alt="Add Goal" class="w-8 h-8 inline">
            </a>
            <a href="{% url 'add_habit' %}" class="bg-yellow-200 text-gray-800 py-2 px-3 rounded-lg hover:bg-yellow-300">
                <img src="{% static 'habits/icons/add_habit.png' %}" alt="Add Habit" class="w-8 h-8 inline">
            </a>
        </div>

        <div class="flex flex-wrap md:flex-nowrap mt-4">
            <!-- Left Column -->
            <div class="flex flex-col w-full md:w-2/3 space-y-4">
                <div class="p-4">
                    <h2 class="text-2xl font-semibold mb-4 text-center text-gray-800">Add Study Time</h2>
                    <form method="post" id="studyTimeForm" class="bg-white p-4 rounded-lg shadow-lg">
                        {% csrf_token %}
                        <div class="mb-4">
                            <label for="study_time_input" class="block text-lg font-medium mb-2 text-gray-700">Study time:</label>
                            {{ form.study_time|add_class:"w-full px-3 py-2 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-300 bg-gray-100 text-gray-700" }}
                        </div>
                        <div class="mb-4">
                            <label for="id_category" class="block text-lg font-medium mb-2 text-gray-700">Category:</label>
                            {{ form.category|add_class:"w-full px-3 py-2 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-300 bg-gray-100 text-gray-700" }}
                        </div>
                        <div class="mb-4">
                            <label for="timer" class="block text-lg font-medium mb-2 text-gray-700">Timer</label>
                            <div id="timer" class="form-control form-control-lg mt-2 bg-gray-100 text-gray-700 py-2 px-4 rounded-lg">00:00:00</div>
                            <div class="flex space-x-2 mt-2" aria-label="Timer controls" id="timer_controls">
                                <button type="button" class="bg-green-200 text-gray-800 py-2 px-4 rounded-lg hover:bg-green-300" onclick="startTimer()">
                                    <img src="{% static 'habits/icons/start.png' %}" alt="Start" class="w-5 h-5 inline"> Start
                                </button>
                                <button type="button" class="bg-yellow-200 text-gray-800 py-2 px-4 rounded-lg hover:bg-yellow-300" onclick="pauseTimer()">
                                    <img src="{% static 'habits/icons/pause.png' %}" alt="Pause" class="w-5 h-5 inline"> Pause
                                </button>
                                <button type="button" class="bg-red-200 text-gray-800 py-2 px-4 rounded-lg hover:bg-red-300" onclick="resetTimer()">
                                    <img src="{% static 'habits/icons/reset.png' %}" alt="Reset" class="w-5 h-5 inline"> Reset
                                </button>
                            </div>
                        </div>
                        <input type="hidden" name="study_time" id="study_time_hidden">
                        <button type="submit" class="bg-blue-200 text-gray-800 py-2 px-4 rounded-lg mt-3 hover:bg-blue-300" onclick="submitForm()">
                            <img src="{% static 'habits/icons/save.png' %}" alt="Save" class="w-5 h-5 inline"> Save
                        </button>
                        <a href="{% url 'index' %}" class="bg-gray-200 text-gray-800 py-2 px-4 rounded-lg mt-3 hover:bg-gray-300">
                            <img src="{% static 'habits/icons/delete.png' %}" alt="Cancel" class="w-5 h-5 inline"> Cancel
                        </a>
                    </form>

                    <script>
                        let timer;
                        let startTime;
                        let updatedTime;
                        let difference;
                        let tInterval;
                        let savedTime;
                        let running = false;
                        let paused = false;
                        let useTimer = false;

                        function toggleTimerManual() {
                            useTimer = !useTimer;
                            const input = document.getElementById('study_time_input');
                            const timerDiv = document.getElementById('timer');
                            const timerControls = document.getElementById('timer_controls');
                            const toggleButton = document.getElementById('toggle_timer_manual');

                            if (useTimer) {
                                input.readOnly = true;
                                timerControls.style.display = 'block';
                                timerDiv.style.display = 'block';
                                input.value = '00:00:00';
                                toggleButton.innerHTML = `<img src="{% static 'habits/icons/toggle.png' %}" alt="Toggle" class="w-5 h-5 inline"> Use Manual`;
                            } else {
                                input.readOnly = false;
                                timerControls.style.display = 'none';
                                timerDiv.style.display = 'none';
                                toggleButton.innerHTML = `<img src="{% static 'habits/icons/toggle.png' %}" alt="Toggle" class="w-5 h-5 inline"> Use Timer`;
                            }
                        }

                        function startTimer() {
                            if (!running) {
                                startTime = new Date().getTime();
                                tInterval = setInterval(getShowTime, 1000);
                                paused = false;
                                running = true;
                            }
                        }

                        function pauseTimer() {
                            if (!paused && running) {
                                clearInterval(tInterval);
                                savedTime = difference;
                                paused = true;
                                running = false;
                            }
                        }

                        function resetTimer() {
                            clearInterval(tInterval);
                            savedTime = 0;
                            difference = 0;
                            paused = false;
                            running = false;
                            document.getElementById("timer").innerHTML = "00:00:00";
                            document.getElementById("study_time_input").value = "00:00:00";
                        }

                        function getShowTime() {
                            updatedTime = new Date().getTime();
                            if (savedTime) {
                                difference = (updatedTime - startTime) + savedTime;
                            } else {
                                difference = updatedTime - startTime;
                            }
                            let hours = Math.floor((difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                            let minutes = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
                            let seconds = Math.floor((difference % (1000 * 60)) / 1000);
                            hours = (hours < 10) ? "0" + hours : hours;
                            minutes = (minutes < 10) ? "0" + minutes : minutes;
                            seconds = (seconds < 10) ? "0" + seconds : seconds;
                            const currentTime = hours + ":" + minutes + ":" + seconds;
                            document.getElementById("timer").innerHTML = currentTime;
                            document.getElementById("study_time_input").value = currentTime;
                        }

                        function submitForm() {
                            const timeArray = document.getElementById("study_time_input").value.split(':');
                            if (timeArray.length === 3) {
                                const hours = parseInt(timeArray[0]);
                                const minutes = parseInt(timeArray[1]);
                                const seconds = parseInt(timeArray[2]);
                                const totalMinutes = (hours * 60) + minutes + (seconds / 60);
                                document.getElementById("study_time_hidden").value = totalMinutes.toFixed(2);
                            } else {
                                document.getElementById("study_time_hidden").value = document.getElementById("study_time_input").value;
                            }
                            document.getElementById("studyTimeForm").submit();
                        }

                        window.onload = function() {
                            toggleTimerManual(); // Set initial state to use input manually
                        }
                    </script>
                </div>

                <div class="p-4">
                    <div class="card bg-white rounded-lg shadow-lg">
                        <div class="card-header text-xl font-semibold bg-gray-200 p-4 rounded-t-lg text-gray-800">
                            Goals
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for goal in goals %}
                                <li class="list-group-item flex justify-between items-center bg-white text-gray-800 p-4 border-b border-gray-200">
                                    <span><strong>{{ goal.category.name }}:</strong> {{ goal.goal }} hours in {{ goal.month.name }}</span>
                                    <div class="flex space-x-2">
                                        <a href="{% url 'update_goal' goal.id %}" class="bg-yellow-200 text-gray-800 py-1 px-3 rounded-lg hover:bg-yellow-300">
                                            <img src="{% static 'habits/icons/update.png' %}" alt="Update" class="w-5 h-5 inline"> Update
                                        </a>
                                        <a href="{% url 'delete_goal' goal.id %}" class="bg-red-200 text-gray-800 py-1 px-3 rounded-lg hover:bg-red-300">
                                            <img src="{% static 'habits/icons/delete.png' %}" alt="Delete" class="w-5 h-5 inline"> Delete
                                        </a>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="p-4">
                    <div class="card bg-white rounded-lg shadow-lg">
                        <div class="card-header text-xl font-semibold bg-gray-200 p-4 rounded-t-lg text-gray-800">
                            Study Days
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for study in study_days %}
                                <li class="list-group-item flex justify-between items-center bg-white text-gray-800 p-4 border-b border-gray-200">
                                    <strong>{{ study.category.name }}:</strong> {{ study.study_time }} hours on {{ study.date_current }}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <!-- Right Column -->
            <div class="w-full md:w-1/1 p-4">
                <div class="card bg-white rounded-lg shadow-lg">
                    <div class="card-header text-xl font-semibold bg-gray-200 p-4 rounded-t-lg text-gray-800">
                        Study Goals and Progress Chart
                    </div>
                    <div class="card-body p-4">
                        <img src="data:image/png;base64,{{ chart }}" alt="Chart" class="img-fluid rounded-lg shadow-lg">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

habits/templates/habits/update_goal.html
{% extends 'habits/base.html' %}

{% block title %}Update Goal - ImProductive{% endblock %}

{% block content %}
    <h1 class="mt-4">Update Goal</h1>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}